#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# TG 云盘 · 一键部署脚本（quickstart）
#
# 做什么：
#   1. 检查依赖（docker / openssl）
#   2. 交互式问 2 个 Telegram 值（Bot Token + Channel ID）
#   3. 自动生成 7 个强随机密钥
#   4. 写入 .env（基于 .env.example 模板，置 NODE_ENV=development）
#   5. 生成自签 TLS 证书（make certs-dev 等价逻辑）
#   6. docker compose up -d --build
#   7. 等 Postgres 就绪后 seed 出管理员账号
#   8. 打印访问 URL + 管理员密码（首次登录后必须改密）
#
# 不做什么：
#   - 不部署 Cloudflare Worker（国内直连优化，独立后跑 make worker-deploy）
#   - 不配置 SMTP（dev 模式下验证码直接在 API 响应里返回）
#   - 不申请 Let's Encrypt（生产部署独立按启动指南第七节做）
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# 切到脚本所在目录（保证相对路径稳定）
cd "$(dirname "$0")"

# ─── 颜色 ────────────────────────────────────────────────────────────────────
if [ -t 1 ]; then
  C_RESET=$'\033[0m'; C_BOLD=$'\033[1m'
  C_RED=$'\033[31m'; C_GREEN=$'\033[32m'; C_YELLOW=$'\033[33m'; C_CYAN=$'\033[36m'
else
  C_RESET=""; C_BOLD=""; C_RED=""; C_GREEN=""; C_YELLOW=""; C_CYAN=""
fi

say()  { printf '%s\n' "$*"; }
ok()   { printf '%s✅ %s%s\n' "$C_GREEN" "$*" "$C_RESET"; }
warn() { printf '%s⚠️  %s%s\n' "$C_YELLOW" "$*" "$C_RESET"; }
err()  { printf '%s❌ %s%s\n' "$C_RED" "$*" "$C_RESET" >&2; }
hdr()  { printf '\n%s── %s ──%s\n' "$C_BOLD$C_CYAN" "$*" "$C_RESET"; }

# ─── 0. 依赖检查 ─────────────────────────────────────────────────────────────
hdr "Step 0/7  依赖检查"

need() {
  if ! command -v "$1" >/dev/null 2>&1; then
    err "缺少依赖：$1"
    say "$2"
    exit 1
  fi
  ok "已找到 $1"
}

need docker   "请安装 Docker Desktop：https://www.docker.com/products/docker-desktop"
need openssl  "请安装 openssl（macOS/Linux 自带；Windows 用 Git Bash 自带）"

# docker compose（v2 子命令）或 docker-compose（v1）二选一
if docker compose version >/dev/null 2>&1; then
  DC="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
  DC="docker-compose"
else
  err "未找到 docker compose（v2 子命令）或 docker-compose（v1）"
  exit 1
fi
ok "已找到 $DC"

# ─── 1. 防覆盖已有 .env ──────────────────────────────────────────────────────
hdr "Step 1/7  .env 状态检查"

if [ -f .env ]; then
  warn "项目已存在 .env"
  say "    覆盖现有 .env 会清掉你已有的密钥（包括数据库密码 — 已有数据将无法解密）"
  printf "    确认覆盖？输入 ${C_BOLD}yes${C_RESET} 继续，其他任意键退出： "
  read -r confirm
  if [ "$confirm" != "yes" ]; then
    say "已取消。如需仅启动服务，直接运行：$DC up -d"
    exit 0
  fi
  cp .env ".env.backup.$(date +%Y%m%d-%H%M%S)"
  ok "已备份旧 .env 到 .env.backup.*"
fi

# ─── 2. 交互式问 Telegram 两值 ───────────────────────────────────────────────
hdr "Step 2/7  Telegram 配置（必填，无法自动生成）"

say ""
say "  TG 云盘把文件存在 Telegram 私有频道。需要："
say ""
say "  ${C_BOLD}① Bot Token${C_RESET}"
say "     • 打开 Telegram，搜索 ${C_CYAN}@BotFather${C_RESET}"
say "     • 发 /newbot，按提示起名"
say "     • 复制返回的 token（形如 ${C_CYAN}123456789:ABCdefGHIjklMNOpqrSTUvwxYZ${C_RESET}）"
say ""
say "  ${C_BOLD}② Channel ID${C_RESET}"
say "     • 在 Telegram 新建 ${C_CYAN}私有频道${C_RESET}（Private Channel）"
say "     • 把刚才的 Bot 加为${C_CYAN}管理员${C_RESET}（必须，否则无法上传）"
say "     • 拿 ID 的最简办法：在频道里发任意一条消息，转发给 @userinfobot"
say "       → 它会回复 \"Forwarded from chat: ${C_CYAN}-100xxxxxxxxxx${C_RESET}\"，那串就是 ID"
say "     • Channel ID 永远以 ${C_CYAN}-100${C_RESET} 开头"
say ""

while :; do
  printf "  TG_BOT_TOKEN: "
  read -r TG_BOT_TOKEN
  if [[ "$TG_BOT_TOKEN" =~ ^[0-9]+:[A-Za-z0-9_-]{30,}$ ]]; then
    break
  fi
  warn "格式不对。应形如 123456789:ABCdef...（数字:字母数字混合）。重试。"
done

while :; do
  printf "  TG_CHANNEL_ID（-100 开头）: "
  read -r TG_CHANNEL_ID
  if [[ "$TG_CHANNEL_ID" =~ ^-100[0-9]+$ ]]; then
    break
  fi
  warn "格式不对。私有频道 ID 必须以 -100 开头，后跟数字。重试。"
done

ok "Telegram 配置已收集"

# ─── 3. 自动生成随机密钥 ─────────────────────────────────────────────────────
hdr "Step 3/7  生成 7 个强随机密钥"

# hex(64 字节) = 128 字符；hex(32 字节) = 64 字符（ENCRYPTION_MASTER_KEY 要求恰好 64）
JWT_SECRET="$(openssl rand -hex 64)"
JWT_REFRESH_SECRET="$(openssl rand -hex 64)"
ENCRYPTION_MASTER_KEY="$(openssl rand -hex 32)"

# 数据库 / Redis / Workers secret：alphanumeric，避免 URL/shell 转义
gen_alnum() { openssl rand -base64 48 | tr -d '=+/' | head -c "$1"; }
DB_PASS="$(gen_alnum 40)"
REDIS_PASS="$(gen_alnum 40)"
CF_WORKERS_SECRET="$(gen_alnum 40)"

# 管理员初始密码：24 位 alphanumeric，要打印给用户
ADMIN_INITIAL_PASSWORD="$(gen_alnum 24)"

ok "密钥已生成（不会写入终端历史，仅落 .env）"

# ─── 4. 写入 .env ────────────────────────────────────────────────────────────
hdr "Step 4/7  写入 .env"

# 用 here-doc 直接写完整 .env，不依赖跨平台 sed 行为
cat > .env <<EOF
# Auto-generated by quickstart.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT commit this file. .gitignore covers it.

# ─── Application ─────────────────────────────────────────────────────────────
# dev 模式：API 文档挂载在 /api/docs；验证码直接在 API 响应里返回（无需 SMTP）
NODE_ENV=development
PORT=3000
APP_URL=https://localhost

# ─── Database ────────────────────────────────────────────────────────────────
DB_NAME=tgpan
DB_USER=tgpan
DB_PASS=${DB_PASS}
DATABASE_URL=postgresql://tgpan:${DB_PASS}@postgres:5432/tgpan
DATABASE_SSL=false

# ─── Redis ───────────────────────────────────────────────────────────────────
REDIS_URL=redis://:${REDIS_PASS}@redis:6379
REDIS_PASS=${REDIS_PASS}

# ─── JWT / Auth ──────────────────────────────────────────────────────────────
JWT_SECRET=${JWT_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}

# ─── Encryption ──────────────────────────────────────────────────────────────
ENCRYPTION_MASTER_KEY=${ENCRYPTION_MASTER_KEY}

# ─── Telegram Bot ────────────────────────────────────────────────────────────
TG_BOT_TOKEN=${TG_BOT_TOKEN}
TG_CHANNEL_ID=${TG_CHANNEL_ID}

# ─── Cloudflare Workers（可选，国内直连用 — 跳过则后端直连 telegram.org） ────
CF_WORKERS_URL=
CF_WORKERS_SECRET=${CF_WORKERS_SECRET}

# ─── SMTP（dev 模式不发邮件，留占位即可） ───────────────────────────────────
SMTP_HOST=smtp.example.com
SMTP_PORT=587
SMTP_USER=noreply@example.com
SMTP_PASS=placeholder_smtp_dev_mode
SMTP_FROM=TG云盘 <noreply@example.com>

# ─── Storage & Limits ────────────────────────────────────────────────────────
DEFAULT_USER_QUOTA_GB=50
MAX_FOLDERS_PER_DIR=10
TRASH_RETENTION_DAYS=30

# ─── Admin ───────────────────────────────────────────────────────────────────
ADMIN_USERNAME=admin
ADMIN_INITIAL_PASSWORD=${ADMIN_INITIAL_PASSWORD}

# ─── Frontend Build-time ─────────────────────────────────────────────────────
VITE_API_BASE_URL=/api

# ─── Docker / Compose ────────────────────────────────────────────────────────
BACKEND_PORT=3000
EOF

chmod 600 .env || true  # Windows / 部分 FS 可能不支持，忽略错误
ok ".env 已写入并设为仅当前用户可读"

# ─── 5. 自签 TLS 证书 ────────────────────────────────────────────────────────
hdr "Step 5/7  自签 TLS 证书（开发用）"

if [ -f certs/fullchain.pem ] && [ -f certs/privkey.pem ]; then
  ok "证书已存在，跳过生成"
else
  mkdir -p certs/acme-webroot
  say "  生成 4096-bit 自签证书（CN=localhost，10 年有效）..."
  docker run --rm -v "$(pwd)/certs:/certs" alpine/openssl req -x509 -nodes -days 3650 \
    -newkey rsa:4096 \
    -keyout /certs/privkey.pem -out /certs/fullchain.pem \
    -subj "/CN=localhost" \
    -addext "subjectAltName=DNS:localhost,DNS:*.localhost,IP:127.0.0.1" \
    >/dev/null 2>&1
  ok "证书已生成至 certs/（浏览器首次访问会警告，开发期点'高级 → 继续'即可）"
fi

# ─── 6. 启动容器 ─────────────────────────────────────────────────────────────
hdr "Step 6/7  构建并启动容器（首次约 3-5 分钟）"

$DC up -d --build

say ""
say "  等待 Postgres 就绪..."
for i in $(seq 1 60); do
  if $DC exec -T postgres pg_isready -U tgpan -d tgpan >/dev/null 2>&1; then
    ok "Postgres 已就绪"
    break
  fi
  sleep 2
  if [ "$i" = "60" ]; then
    err "Postgres 启动超时（120s）。请查看日志：$DC logs postgres"
    exit 1
  fi
done

# ─── 7. Seed 管理员账号 ──────────────────────────────────────────────────────
hdr "Step 7/7  初始化数据库 + 创建管理员"

if $DC exec -T backend npx ts-node src/database/seed.ts; then
  ok "管理员账号已创建"
else
  err "seed 失败。可能后端还没起来。等 10 秒后手动重试："
  say "    $DC exec backend npx ts-node src/database/seed.ts"
  exit 1
fi

# ─── 完工 ────────────────────────────────────────────────────────────────────
say ""
say "${C_GREEN}${C_BOLD}════════════════════════════════════════════════════════════════════${C_RESET}"
say "${C_GREEN}${C_BOLD}  🎉 部署完成${C_RESET}"
say "${C_GREEN}${C_BOLD}════════════════════════════════════════════════════════════════════${C_RESET}"
say ""
say "  访问地址：${C_CYAN}https://localhost${C_RESET}"
say "  API 文档：${C_CYAN}https://localhost/api/docs${C_RESET}（dev 模式才挂载）"
say ""
say "  管理员账号："
say "    用户名：${C_BOLD}admin${C_RESET}"
say "    初始密码：${C_BOLD}${ADMIN_INITIAL_PASSWORD}${C_RESET}"
say ""
say "  ${C_YELLOW}⚠️  首次登录后请立即在管理后台改密。${C_RESET}"
say "  ${C_YELLOW}⚠️  自签证书：浏览器会警告 \"您的连接不是私密连接\"，点'高级 → 继续'。${C_RESET}"
say ""
say "  常用命令："
say "    查看日志：${C_CYAN}$DC logs -f${C_RESET}"
say "    停止：    ${C_CYAN}$DC down${C_RESET}"
say "    重启：    ${C_CYAN}$DC restart${C_RESET}"
say ""
say "  下一步（可选）："
say "    • 国内直连优化：部署 Cloudflare Worker（${C_CYAN}make worker-deploy${C_RESET}）"
say "    • 公网部署：    见 ${C_CYAN}启动指南.md${C_RESET} 第七节"
say ""
